elasticsearch:
  image: elasticsearch:latest
  expose:
    - 9200
  ports:
    - 9200:9200
#  environment:

#  volumes:
#    -  /tmp/postgresdb:/var/lib/postgresql/data

kibana:
  image: kibana:latest 
  expose:
    - 5601
  ports:
    - 5601:5601 
  links:
    - elasticsearch



